config/routes.rb
Rails.application.routes.draw do
  resources :cats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
require 'action_view'

require 'action_view'
class Cat < ApplicationRecord

    include ActionView::Helpers::DateHelper

    CAT_COLORS = [:black, :white, :orange, :brown]

    validates :color, inclusion: CAT_COLORS
    validates :birthdate, :color, :name, :sex , presence:true

    has_many :rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    depndent: :destroy

    def age
        time_ago_in_words(birth_date)
    end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
    
    STATUS= [:pending , :denied , :pending]

    validates :cat_id, :end_date, :start_date, :status, presence: true
    validates :status, inclusion: STATUS

    belongs_to :cat,
    foreign_key: :cat_id,
    class_name: Cat:

    after_initialize :overlapping_approved_requests

    def pending?
        self.status == 'PENDING'
    end
    
    def overlapping_approved_requests
        overlapping_requests.where('status = \'APPROVED\'')
    end
    
    def overlapping_pending_requests
        overlapping_requests.where('status = \'PENDING\'')
    end

    def approve!
        raise 'not pending'  if self.status != 'PENDING'
        self.status = 'APPROVED'
        self.save!
    
        overlapping_pending_requests.each do |req|
            req.update!(status: 'DENIED')
        end
    end
    
    def approved?
    self.status == 'APPROVED'
    end

    def denied?
        self.status == 'DENIED'
    end

    def deny!
        self.status = 'DENIED'
        self.save!
    end


    def overlapping_requests
        CatRentalRequest
        .where.not(id: self.id)
        .where(cat_id: cat_id)
        .where.not('start_date > :end_date OR end_date < :start_date',
                    start_date: start_date, end_date: end_date)
    end

    def does_not_overlap_approved_request
        return if self.denied?
        msg = 'Request conflicts with existing approved request'
        errors[:base] << msg unless overlapping_approved_requests.empty?
    end
    
    def start_must_come_before_end
        return if start_date < end_date
        errors[:start_date] << 'must come before end date'
        errors[:end_date] << 'must come after start date'
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    def approve
      current_cat_rental_request.approve!
      redirect_to cat_url(current_cat)
    end
  
    def create
      @rental_request = CatRentalRequest.new(cat_rental_request_params)
      if @rental_request.save
        redirect_to cat_url(@rental_request.cat)
      else
        flash.now[:errors] = @rental_request.errors.full_messages
        render :new
      end
    end
  
    def deny
      current_cat_rental_request.deny!
      redirect_to cat_url(current_cat)
    end
  
    def new
      @rental_request = CatRentalRequest.new
    end
  
    private
  
    def current_cat_rental_request
      @rental_request ||=
        CatRentalRequest.includes(:cat).find(params[:id])
    end
  
    def current_cat
      current_cat_rental_request.cat
    end
  
    def cat_rental_request_params
      params.require(:cat_rental_request).permit(:cat_id, :end_date, :start_date, :status)
    end
  end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    set_cat
  end

  # GET /cats/new
  def new
    @cat = Cat.new
    redirect_to cat_url(@cat)
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
      flash.now[:notice] = "Great Job creating #{@cat.name}!!"
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_with(model: cat, local: true) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

  <%= form_tag(cats_path) do %>
    <div class = "form-group">
      <%= label_tag 'name', 'Name of Cat'%>
      <%= text_field_tag 'name'%>
      <br>
      
      <%= label_tag 'sex_f', "Female" %>
      <%= radio_button_tag 'sex', "f" %>
      <%= label_tag 'sex_m', "Male" %>
      <%= radio_button_tag 'sex', 'm '%>

      <br>
    </div>

    <div class = "form-group">
      <p> Select the color of cat </p>
      <%= select_tag("color", options_for_select(["blue", "white", "orange", "yellow", "green"])) %>
    </div>
    <br>

    <div class = "form-group">
      <%# <%= label_tag 'description', 'Cat Bio:'%> 
      <p> cat description <p>
      <%= text_area_tag 'description' %>
    </div>
    <br>

    <%= submit_tag "make the cat" %>
  <% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cats</h1>

<table>
  <thead>
    <tr>
      <th>Birth date</th>
      <th>Color</th>
      <th>Name</th>
      <th>Sex</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.birth_date %></td>
        <td><%= cat.color %></td>
        <td><%= cat.name %></td>
        <td><%= cat.sex %></td>
        <td><%= cat.description %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Birth date:</strong>
  <%= @cat.birth_date %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cat.color %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @cat.sex %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cat.description %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninecats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>